// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PreAuthBe.Data;

#nullable disable

namespace PreAuthBe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PreAuthBe.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a9b-8c7d-123456abcdef"),
                            CreatedAt = new DateTime(2025, 10, 17, 11, 19, 11, 841, DateTimeKind.Utc).AddTicks(2794),
                            Email = "somying.j@system.io",
                            FirstName = "สมหญิง",
                            LastName = "ใจดี",
                            PasswordHash = "$2a$11$c0b57bHqaQ/WcgcMHagaROg5BGK5GyLDr1keMYgvucQXmoB4HXE.W",
                            Role = "Admin",
                            Username = "somying_admin"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b8c-9d6e-234567abcdef"),
                            CreatedAt = new DateTime(2025, 10, 17, 11, 19, 11, 841, DateTimeKind.Utc).AddTicks(2817),
                            Email = "somchai.r@email.com",
                            FirstName = "สมชาย",
                            LastName = "รักไทย",
                            PasswordHash = "$2a$11$c0b57bHqaQ/WcgcMHagaROg5BGK5GyLDr1keMYgvucQXmoB4HXE.W",
                            Role = "User",
                            Username = "somchai_user"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4c5b-af4f-345678abcdef"),
                            CreatedAt = new DateTime(2025, 10, 17, 11, 19, 11, 841, DateTimeKind.Utc).AddTicks(2820),
                            Email = "ekachai@superuser.com",
                            FirstName = "เอกชัย",
                            LastName = "ราชา",
                            PasswordHash = "$2a$11$c0b57bHqaQ/WcgcMHagaROg5BGK5GyLDr1keMYgvucQXmoB4HXE.W",
                            Role = "Admin",
                            Username = "ekachai_admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
